//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("starwarsModel", "FK_CourseGrade_Course", "Courses", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(web.Models.Course), "CourseGrades", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(web.Models.CourseGrade), true)]
[assembly: EdmRelationshipAttribute("starwarsModel", "FK_CourseGrade_User", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(web.Models.User), "CourseGrades", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(web.Models.CourseGrade), true)]
[assembly: EdmRelationshipAttribute("starwarsModel", "FK_CourseInstance_Course", "Courses", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(web.Models.Course), "CourseInstances", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(web.Models.CourseInstance), true)]
[assembly: EdmRelationshipAttribute("starwarsModel", "FK_CourseParts_GradeType", "GradeType", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(web.Models.GradeType), "CourseParts", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(web.Models.CoursePart), true)]
[assembly: EdmRelationshipAttribute("starwarsModel", "FK_Result_CourseInstance", "CourseParts", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(web.Models.CoursePart), "Results", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(web.Models.Result), true)]
[assembly: EdmRelationshipAttribute("starwarsModel", "FK_Result_User", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(web.Models.User), "Results", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(web.Models.Result), true)]

#endregion

namespace web.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class starwarsEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new starwarsEntities1 object using the connection string found in the 'starwarsEntities1' section of the application configuration file.
        /// </summary>
        public starwarsEntities1() : base("name=starwarsEntities1", "starwarsEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new starwarsEntities1 object.
        /// </summary>
        public starwarsEntities1(string connectionString) : base(connectionString, "starwarsEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new starwarsEntities1 object.
        /// </summary>
        public starwarsEntities1(EntityConnection connection) : base(connection, "starwarsEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CourseGrade> CourseGrades
        {
            get
            {
                if ((_CourseGrades == null))
                {
                    _CourseGrades = base.CreateObjectSet<CourseGrade>("CourseGrades");
                }
                return _CourseGrades;
            }
        }
        private ObjectSet<CourseGrade> _CourseGrades;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CourseInstance> CourseInstances
        {
            get
            {
                if ((_CourseInstances == null))
                {
                    _CourseInstances = base.CreateObjectSet<CourseInstance>("CourseInstances");
                }
                return _CourseInstances;
            }
        }
        private ObjectSet<CourseInstance> _CourseInstances;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CoursePart> CourseParts
        {
            get
            {
                if ((_CourseParts == null))
                {
                    _CourseParts = base.CreateObjectSet<CoursePart>("CourseParts");
                }
                return _CourseParts;
            }
        }
        private ObjectSet<CoursePart> _CourseParts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Course> Courses
        {
            get
            {
                if ((_Courses == null))
                {
                    _Courses = base.CreateObjectSet<Course>("Courses");
                }
                return _Courses;
            }
        }
        private ObjectSet<Course> _Courses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GradeType> GradeTypes
        {
            get
            {
                if ((_GradeTypes == null))
                {
                    _GradeTypes = base.CreateObjectSet<GradeType>("GradeTypes");
                }
                return _GradeTypes;
            }
        }
        private ObjectSet<GradeType> _GradeTypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Result> Results
        {
            get
            {
                if ((_Results == null))
                {
                    _Results = base.CreateObjectSet<Result>("Results");
                }
                return _Results;
            }
        }
        private ObjectSet<Result> _Results;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CourseGrades EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCourseGrades(CourseGrade courseGrade)
        {
            base.AddObject("CourseGrades", courseGrade);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CourseInstances EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCourseInstances(CourseInstance courseInstance)
        {
            base.AddObject("CourseInstances", courseInstance);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CourseParts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCourseParts(CoursePart coursePart)
        {
            base.AddObject("CourseParts", coursePart);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Courses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCourses(Course course)
        {
            base.AddObject("Courses", course);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GradeTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGradeTypes(GradeType gradeType)
        {
            base.AddObject("GradeTypes", gradeType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Results EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToResults(Result result)
        {
            base.AddObject("Results", result);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="starwarsModel", Name="Course")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Course : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Course object.
        /// </summary>
        /// <param name="courseID">Initial value of the courseID property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="points">Initial value of the points property.</param>
        public static Course CreateCourse(global::System.String courseID, global::System.String name, global::System.Double points)
        {
            Course course = new Course();
            course.courseID = courseID;
            course.name = name;
            course.points = points;
            return course;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String courseID
        {
            get
            {
                return _courseID;
            }
            set
            {
                if (_courseID != value)
                {
                    OncourseIDChanging(value);
                    ReportPropertyChanging("courseID");
                    _courseID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("courseID");
                    OncourseIDChanged();
                }
            }
        }
        private global::System.String _courseID;
        partial void OncourseIDChanging(global::System.String value);
        partial void OncourseIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double points
        {
            get
            {
                return _points;
            }
            set
            {
                OnpointsChanging(value);
                ReportPropertyChanging("points");
                _points = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("points");
                OnpointsChanged();
            }
        }
        private global::System.Double _points;
        partial void OnpointsChanging(global::System.Double value);
        partial void OnpointsChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("starwarsModel", "FK_CourseGrade_Course", "CourseGrades")]
        public EntityCollection<CourseGrade> CourseGrades
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CourseGrade>("starwarsModel.FK_CourseGrade_Course", "CourseGrades");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CourseGrade>("starwarsModel.FK_CourseGrade_Course", "CourseGrades", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("starwarsModel", "FK_CourseInstance_Course", "CourseInstances")]
        public EntityCollection<CourseInstance> CourseInstances
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CourseInstance>("starwarsModel.FK_CourseInstance_Course", "CourseInstances");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CourseInstance>("starwarsModel.FK_CourseInstance_Course", "CourseInstances", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="starwarsModel", Name="CourseGrade")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CourseGrade : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CourseGrade object.
        /// </summary>
        /// <param name="userID">Initial value of the userID property.</param>
        /// <param name="courseID">Initial value of the courseID property.</param>
        /// <param name="grade">Initial value of the grade property.</param>
        public static CourseGrade CreateCourseGrade(global::System.Int32 userID, global::System.String courseID, global::System.String grade)
        {
            CourseGrade courseGrade = new CourseGrade();
            courseGrade.userID = userID;
            courseGrade.courseID = courseID;
            courseGrade.grade = grade;
            return courseGrade;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 userID
        {
            get
            {
                return _userID;
            }
            set
            {
                if (_userID != value)
                {
                    OnuserIDChanging(value);
                    ReportPropertyChanging("userID");
                    _userID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("userID");
                    OnuserIDChanged();
                }
            }
        }
        private global::System.Int32 _userID;
        partial void OnuserIDChanging(global::System.Int32 value);
        partial void OnuserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String courseID
        {
            get
            {
                return _courseID;
            }
            set
            {
                if (_courseID != value)
                {
                    OncourseIDChanging(value);
                    ReportPropertyChanging("courseID");
                    _courseID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("courseID");
                    OncourseIDChanged();
                }
            }
        }
        private global::System.String _courseID;
        partial void OncourseIDChanging(global::System.String value);
        partial void OncourseIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String grade
        {
            get
            {
                return _grade;
            }
            set
            {
                OngradeChanging(value);
                ReportPropertyChanging("grade");
                _grade = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("grade");
                OngradeChanged();
            }
        }
        private global::System.String _grade;
        partial void OngradeChanging(global::System.String value);
        partial void OngradeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("starwarsModel", "FK_CourseGrade_Course", "Courses")]
        public Course Course
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Course>("starwarsModel.FK_CourseGrade_Course", "Courses").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Course>("starwarsModel.FK_CourseGrade_Course", "Courses").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Course> CourseReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Course>("starwarsModel.FK_CourseGrade_Course", "Courses");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Course>("starwarsModel.FK_CourseGrade_Course", "Courses", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("starwarsModel", "FK_CourseGrade_User", "Users")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("starwarsModel.FK_CourseGrade_User", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("starwarsModel.FK_CourseGrade_User", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("starwarsModel.FK_CourseGrade_User", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("starwarsModel.FK_CourseGrade_User", "Users", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="starwarsModel", Name="CourseInstance")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CourseInstance : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CourseInstance object.
        /// </summary>
        /// <param name="instanceID">Initial value of the instanceID property.</param>
        /// <param name="courseID">Initial value of the courseID property.</param>
        public static CourseInstance CreateCourseInstance(global::System.String instanceID, global::System.String courseID)
        {
            CourseInstance courseInstance = new CourseInstance();
            courseInstance.instanceID = instanceID;
            courseInstance.courseID = courseID;
            return courseInstance;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String instanceID
        {
            get
            {
                return _instanceID;
            }
            set
            {
                if (_instanceID != value)
                {
                    OninstanceIDChanging(value);
                    ReportPropertyChanging("instanceID");
                    _instanceID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("instanceID");
                    OninstanceIDChanged();
                }
            }
        }
        private global::System.String _instanceID;
        partial void OninstanceIDChanging(global::System.String value);
        partial void OninstanceIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String courseID
        {
            get
            {
                return _courseID;
            }
            set
            {
                OncourseIDChanging(value);
                ReportPropertyChanging("courseID");
                _courseID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("courseID");
                OncourseIDChanged();
            }
        }
        private global::System.String _courseID;
        partial void OncourseIDChanging(global::System.String value);
        partial void OncourseIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("starwarsModel", "FK_CourseInstance_Course", "Courses")]
        public Course Course
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Course>("starwarsModel.FK_CourseInstance_Course", "Courses").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Course>("starwarsModel.FK_CourseInstance_Course", "Courses").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Course> CourseReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Course>("starwarsModel.FK_CourseInstance_Course", "Courses");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Course>("starwarsModel.FK_CourseInstance_Course", "Courses", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="starwarsModel", Name="CoursePart")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CoursePart : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CoursePart object.
        /// </summary>
        /// <param name="partID">Initial value of the partID property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="instanceID">Initial value of the instanceID property.</param>
        public static CoursePart CreateCoursePart(global::System.Int32 partID, global::System.String name, global::System.String instanceID)
        {
            CoursePart coursePart = new CoursePart();
            coursePart.partID = partID;
            coursePart.name = name;
            coursePart.instanceID = instanceID;
            return coursePart;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 partID
        {
            get
            {
                return _partID;
            }
            set
            {
                if (_partID != value)
                {
                    OnpartIDChanging(value);
                    ReportPropertyChanging("partID");
                    _partID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("partID");
                    OnpartIDChanged();
                }
            }
        }
        private global::System.Int32 _partID;
        partial void OnpartIDChanging(global::System.Int32 value);
        partial void OnpartIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String instanceID
        {
            get
            {
                return _instanceID;
            }
            set
            {
                OninstanceIDChanging(value);
                ReportPropertyChanging("instanceID");
                _instanceID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("instanceID");
                OninstanceIDChanged();
            }
        }
        private global::System.String _instanceID;
        partial void OninstanceIDChanging(global::System.String value);
        partial void OninstanceIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> weight
        {
            get
            {
                return _weight;
            }
            set
            {
                OnweightChanging(value);
                ReportPropertyChanging("weight");
                _weight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("weight");
                OnweightChanged();
            }
        }
        private Nullable<global::System.Double> _weight;
        partial void OnweightChanging(Nullable<global::System.Double> value);
        partial void OnweightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> points
        {
            get
            {
                return _points;
            }
            set
            {
                OnpointsChanging(value);
                ReportPropertyChanging("points");
                _points = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("points");
                OnpointsChanged();
            }
        }
        private Nullable<global::System.Double> _points;
        partial void OnpointsChanging(Nullable<global::System.Double> value);
        partial void OnpointsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> gradeType
        {
            get
            {
                return _gradeType;
            }
            set
            {
                OngradeTypeChanging(value);
                ReportPropertyChanging("gradeType");
                _gradeType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("gradeType");
                OngradeTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _gradeType;
        partial void OngradeTypeChanging(Nullable<global::System.Int32> value);
        partial void OngradeTypeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("starwarsModel", "FK_CourseParts_GradeType", "GradeType")]
        public GradeType GradeType1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GradeType>("starwarsModel.FK_CourseParts_GradeType", "GradeType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GradeType>("starwarsModel.FK_CourseParts_GradeType", "GradeType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<GradeType> GradeType1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GradeType>("starwarsModel.FK_CourseParts_GradeType", "GradeType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<GradeType>("starwarsModel.FK_CourseParts_GradeType", "GradeType", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("starwarsModel", "FK_Result_CourseInstance", "Results")]
        public EntityCollection<Result> Results
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Result>("starwarsModel.FK_Result_CourseInstance", "Results");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Result>("starwarsModel.FK_Result_CourseInstance", "Results", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="starwarsModel", Name="GradeType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GradeType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GradeType object.
        /// </summary>
        /// <param name="typeID">Initial value of the typeID property.</param>
        /// <param name="name">Initial value of the name property.</param>
        public static GradeType CreateGradeType(global::System.Int32 typeID, global::System.String name)
        {
            GradeType gradeType = new GradeType();
            gradeType.typeID = typeID;
            gradeType.name = name;
            return gradeType;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 typeID
        {
            get
            {
                return _typeID;
            }
            set
            {
                if (_typeID != value)
                {
                    OntypeIDChanging(value);
                    ReportPropertyChanging("typeID");
                    _typeID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("typeID");
                    OntypeIDChanged();
                }
            }
        }
        private global::System.Int32 _typeID;
        partial void OntypeIDChanging(global::System.Int32 value);
        partial void OntypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("starwarsModel", "FK_CourseParts_GradeType", "CourseParts")]
        public EntityCollection<CoursePart> CourseParts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CoursePart>("starwarsModel.FK_CourseParts_GradeType", "CourseParts");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CoursePart>("starwarsModel.FK_CourseParts_GradeType", "CourseParts", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="starwarsModel", Name="Result")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Result : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Result object.
        /// </summary>
        /// <param name="userID">Initial value of the userID property.</param>
        /// <param name="partID">Initial value of the partID property.</param>
        /// <param name="time">Initial value of the time property.</param>
        public static Result CreateResult(global::System.Int32 userID, global::System.Int32 partID, global::System.DateTime time)
        {
            Result result = new Result();
            result.userID = userID;
            result.partID = partID;
            result.time = time;
            return result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 userID
        {
            get
            {
                return _userID;
            }
            set
            {
                if (_userID != value)
                {
                    OnuserIDChanging(value);
                    ReportPropertyChanging("userID");
                    _userID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("userID");
                    OnuserIDChanged();
                }
            }
        }
        private global::System.Int32 _userID;
        partial void OnuserIDChanging(global::System.Int32 value);
        partial void OnuserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 partID
        {
            get
            {
                return _partID;
            }
            set
            {
                if (_partID != value)
                {
                    OnpartIDChanging(value);
                    ReportPropertyChanging("partID");
                    _partID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("partID");
                    OnpartIDChanged();
                }
            }
        }
        private global::System.Int32 _partID;
        partial void OnpartIDChanging(global::System.Int32 value);
        partial void OnpartIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String value
        {
            get
            {
                return _value;
            }
            set
            {
                OnvalueChanging(value);
                ReportPropertyChanging("value");
                _value = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("value");
                OnvalueChanged();
            }
        }
        private global::System.String _value;
        partial void OnvalueChanging(global::System.String value);
        partial void OnvalueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime time
        {
            get
            {
                return _time;
            }
            set
            {
                OntimeChanging(value);
                ReportPropertyChanging("time");
                _time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("time");
                OntimeChanged();
            }
        }
        private global::System.DateTime _time;
        partial void OntimeChanging(global::System.DateTime value);
        partial void OntimeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("starwarsModel", "FK_Result_CourseInstance", "CourseParts")]
        public CoursePart CoursePart
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CoursePart>("starwarsModel.FK_Result_CourseInstance", "CourseParts").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CoursePart>("starwarsModel.FK_Result_CourseInstance", "CourseParts").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CoursePart> CoursePartReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CoursePart>("starwarsModel.FK_Result_CourseInstance", "CourseParts");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CoursePart>("starwarsModel.FK_Result_CourseInstance", "CourseParts", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("starwarsModel", "FK_Result_User", "Users")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("starwarsModel.FK_Result_User", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("starwarsModel.FK_Result_User", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("starwarsModel.FK_Result_User", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("starwarsModel.FK_Result_User", "Users", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="starwarsModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="starwarsModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="userID">Initial value of the userID property.</param>
        /// <param name="roleID">Initial value of the roleID property.</param>
        /// <param name="login">Initial value of the login property.</param>
        /// <param name="fullname">Initial value of the fullname property.</param>
        /// <param name="password">Initial value of the password property.</param>
        public static User CreateUser(global::System.Int32 userID, global::System.Int32 roleID, global::System.String login, global::System.String fullname, global::System.String password)
        {
            User user = new User();
            user.userID = userID;
            user.roleID = roleID;
            user.login = login;
            user.fullname = fullname;
            user.password = password;
            return user;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 userID
        {
            get
            {
                return _userID;
            }
            set
            {
                if (_userID != value)
                {
                    OnuserIDChanging(value);
                    ReportPropertyChanging("userID");
                    _userID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("userID");
                    OnuserIDChanged();
                }
            }
        }
        private global::System.Int32 _userID;
        partial void OnuserIDChanging(global::System.Int32 value);
        partial void OnuserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 roleID
        {
            get
            {
                return _roleID;
            }
            set
            {
                OnroleIDChanging(value);
                ReportPropertyChanging("roleID");
                _roleID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("roleID");
                OnroleIDChanged();
            }
        }
        private global::System.Int32 _roleID;
        partial void OnroleIDChanging(global::System.Int32 value);
        partial void OnroleIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String login
        {
            get
            {
                return _login;
            }
            set
            {
                OnloginChanging(value);
                ReportPropertyChanging("login");
                _login = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("login");
                OnloginChanged();
            }
        }
        private global::System.String _login;
        partial void OnloginChanging(global::System.String value);
        partial void OnloginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String fullname
        {
            get
            {
                return _fullname;
            }
            set
            {
                OnfullnameChanging(value);
                ReportPropertyChanging("fullname");
                _fullname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("fullname");
                OnfullnameChanged();
            }
        }
        private global::System.String _fullname;
        partial void OnfullnameChanging(global::System.String value);
        partial void OnfullnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("starwarsModel", "FK_CourseGrade_User", "CourseGrades")]
        public EntityCollection<CourseGrade> CourseGrades
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CourseGrade>("starwarsModel.FK_CourseGrade_User", "CourseGrades");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CourseGrade>("starwarsModel.FK_CourseGrade_User", "CourseGrades", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("starwarsModel", "FK_Result_User", "Results")]
        public EntityCollection<Result> Results
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Result>("starwarsModel.FK_Result_User", "Results");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Result>("starwarsModel.FK_Result_User", "Results", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
